package array.gui;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author riani
 */
public class Tulungagung extends javax.swing.JFrame {

    /**
     * Creates new form Frame1
     */
    public Tulungagung() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to  the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jKereta1 = new javax.swing.JLabel();
        jRangkaian1 = new javax.swing.JLabel();
        jAsal1 = new javax.swing.JLabel();
        jTujuan1 = new javax.swing.JLabel();
        jKedatangan1 = new javax.swing.JLabel();
        jKeberangkatan1 = new javax.swing.JLabel();
        jKelas1 = new javax.swing.JLabel();
        jKereta2 = new javax.swing.JLabel();
        jRangkaian2 = new javax.swing.JLabel();
        jAsal2 = new javax.swing.JLabel();
        jTujuan2 = new javax.swing.JLabel();
        jKedatangan2 = new javax.swing.JLabel();
        jKeberangkatan2 = new javax.swing.JLabel();
        jKelas2 = new javax.swing.JLabel();
        jKereta3 = new javax.swing.JLabel();
        jRangkaian3 = new javax.swing.JLabel();
        jAsal3 = new javax.swing.JLabel();
        jTujuan3 = new javax.swing.JLabel();
        jKedatangan3 = new javax.swing.JLabel();
        jKeberangkatan3 = new javax.swing.JLabel();
        jKelas3 = new javax.swing.JLabel();
        jKereta4 = new javax.swing.JLabel();
        jKelas4 = new javax.swing.JLabel();
        jRangkaian4 = new javax.swing.JLabel();
        jAsal4 = new javax.swing.JLabel();
        jTujuan4 = new javax.swing.JLabel();
        jKedatangan4 = new javax.swing.JLabel();
        jKeberangkatan4 = new javax.swing.JLabel();
        jKereta5 = new javax.swing.JLabel();
        jKelas5 = new javax.swing.JLabel();
        jRangkaian5 = new javax.swing.JLabel();
        jAsal5 = new javax.swing.JLabel();
        jTujuan5 = new javax.swing.JLabel();
        jKedatangan5 = new javax.swing.JLabel();
        jKeberangkatan5 = new javax.swing.JLabel();
        jKereta6 = new javax.swing.JLabel();
        jKelas6 = new javax.swing.JLabel();
        jRangkaian6 = new javax.swing.JLabel();
        jAsal6 = new javax.swing.JLabel();
        jTujuan6 = new javax.swing.JLabel();
        jKedatangan6 = new javax.swing.JLabel();
        jKeberangkatan6 = new javax.swing.JLabel();
        jKereta7 = new javax.swing.JLabel();
        jRangkaian7 = new javax.swing.JLabel();
        jAsal7 = new javax.swing.JLabel();
        jTujuan7 = new javax.swing.JLabel();
        jKedatangan7 = new javax.swing.JLabel();
        jKeberangkatan7 = new javax.swing.JLabel();
        jKelas7 = new javax.swing.JLabel();
        jKereta8 = new javax.swing.JLabel();
        jRangkaian8 = new javax.swing.JLabel();
        jAsal8 = new javax.swing.JLabel();
        jTujuan8 = new javax.swing.JLabel();
        jKedatangan8 = new javax.swing.JLabel();
        jKeberangkatan8 = new javax.swing.JLabel();
        jKelas8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Jadwal Kereta Api Stasiun Tulungagung");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 10, 630, 40);

        jComboBox1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Kereta --", "KA Dhoho / Penataran", "KA Gajayana", "KA Majapahit", "KA Malabar", "KA Malioboro Ekspres", "KA Matarmaja " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(570, 120, 210, 30);

        jPanel3.setBackground(new java.awt.Color(255, 102, 0));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Kereta Api");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(40, 0, 120, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Stasiun Asal");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(400, 0, 120, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("No Rangkaian");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(220, 0, 120, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Kelas");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(1160, 0, 110, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Stasiun Tujuan");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(580, 0, 110, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Kedatangan");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(770, 0, 110, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Keberangkatan");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(960, 0, 110, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(20, 250, 1320, 30);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jKereta1.setBackground(new java.awt.Color(0, 0, 0));
        jKereta1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jKereta1);
        jKereta1.setBounds(70, 30, 140, 30);

        jRangkaian1.setBackground(new java.awt.Color(255, 102, 102));
        jRangkaian1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jRangkaian1);
        jRangkaian1.setBounds(250, 30, 140, 30);

        jAsal1.setBackground(new java.awt.Color(255, 102, 102));
        jAsal1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jAsal1);
        jAsal1.setBounds(410, 30, 140, 30);

        jTujuan1.setBackground(new java.awt.Color(255, 102, 102));
        jTujuan1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jTujuan1);
        jTujuan1.setBounds(580, 30, 140, 30);

        jKedatangan1.setBackground(new java.awt.Color(255, 102, 102));
        jKedatangan1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jKedatangan1);
        jKedatangan1.setBounds(790, 30, 140, 30);

        jKeberangkatan1.setBackground(new java.awt.Color(255, 102, 102));
        jKeberangkatan1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jKeberangkatan1);
        jKeberangkatan1.setBounds(980, 30, 140, 30);

        jKelas1.setBackground(new java.awt.Color(255, 102, 102));
        jKelas1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jKelas1);
        jKelas1.setBounds(1180, 30, 150, 30);

        jKereta2.setBackground(new java.awt.Color(255, 102, 102));
        jKereta2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jKereta2);
        jKereta2.setBounds(70, 60, 140, 30);

        jRangkaian2.setBackground(new java.awt.Color(255, 102, 102));
        jRangkaian2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jRangkaian2);
        jRangkaian2.setBounds(250, 60, 140, 30);

        jAsal2.setBackground(new java.awt.Color(255, 102, 102));
        jAsal2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jAsal2);
        jAsal2.setBounds(410, 60, 140, 30);

        jTujuan2.setBackground(new java.awt.Color(255, 102, 102));
        jTujuan2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jTujuan2);
        jTujuan2.setBounds(580, 60, 140, 30);

        jKedatangan2.setBackground(new java.awt.Color(255, 102, 102));
        jKedatangan2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jKedatangan2);
        jKedatangan2.setBounds(790, 60, 140, 30);

        jKeberangkatan2.setBackground(new java.awt.Color(255, 102, 102));
        jKeberangkatan2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jKeberangkatan2);
        jKeberangkatan2.setBounds(980, 60, 140, 30);

        jKelas2.setBackground(new java.awt.Color(255, 102, 102));
        jKelas2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jKelas2);
        jKelas2.setBounds(1180, 60, 150, 30);

        jKereta3.setBackground(new java.awt.Color(255, 102, 102));
        jKereta3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jKereta3);
        jKereta3.setBounds(70, 90, 140, 30);

        jRangkaian3.setBackground(new java.awt.Color(255, 102, 102));
        jRangkaian3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jRangkaian3);
        jRangkaian3.setBounds(250, 90, 140, 30);

        jAsal3.setBackground(new java.awt.Color(255, 102, 102));
        jAsal3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jAsal3);
        jAsal3.setBounds(410, 90, 140, 30);

        jTujuan3.setBackground(new java.awt.Color(255, 102, 102));
        jTujuan3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jTujuan3);
        jTujuan3.setBounds(580, 90, 140, 30);

        jKedatangan3.setBackground(new java.awt.Color(255, 102, 102));
        jKedatangan3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jKedatangan3);
        jKedatangan3.setBounds(790, 90, 140, 30);

        jKeberangkatan3.setBackground(new java.awt.Color(255, 102, 102));
        jKeberangkatan3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jKeberangkatan3);
        jKeberangkatan3.setBounds(980, 90, 140, 30);

        jKelas3.setBackground(new java.awt.Color(255, 102, 102));
        jKelas3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jKelas3);
        jKelas3.setBounds(1180, 90, 150, 30);

        jKereta4.setBackground(new java.awt.Color(255, 102, 102));
        jKereta4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jKereta4);
        jKereta4.setBounds(70, 120, 140, 30);

        jKelas4.setBackground(new java.awt.Color(255, 102, 102));
        jKelas4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jKelas4);
        jKelas4.setBounds(1180, 120, 150, 30);

        jRangkaian4.setBackground(new java.awt.Color(255, 102, 102));
        jRangkaian4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jRangkaian4);
        jRangkaian4.setBounds(250, 120, 140, 30);

        jAsal4.setBackground(new java.awt.Color(255, 102, 102));
        jAsal4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jAsal4);
        jAsal4.setBounds(410, 120, 140, 30);

        jTujuan4.setBackground(new java.awt.Color(255, 102, 102));
        jTujuan4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jTujuan4);
        jTujuan4.setBounds(580, 120, 140, 30);

        jKedatangan4.setBackground(new java.awt.Color(255, 102, 102));
        jKedatangan4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jKedatangan4);
        jKedatangan4.setBounds(790, 120, 140, 30);

        jKeberangkatan4.setBackground(new java.awt.Color(255, 102, 102));
        jKeberangkatan4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jKeberangkatan4);
        jKeberangkatan4.setBounds(980, 120, 140, 30);

        jKereta5.setBackground(new java.awt.Color(255, 102, 102));
        jKereta5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jKereta5);
        jKereta5.setBounds(70, 150, 140, 30);

        jKelas5.setBackground(new java.awt.Color(255, 102, 102));
        jKelas5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jKelas5);
        jKelas5.setBounds(1180, 150, 150, 30);

        jRangkaian5.setBackground(new java.awt.Color(255, 102, 102));
        jRangkaian5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jRangkaian5);
        jRangkaian5.setBounds(250, 150, 140, 30);

        jAsal5.setBackground(new java.awt.Color(255, 102, 102));
        jAsal5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jAsal5);
        jAsal5.setBounds(410, 150, 140, 30);

        jTujuan5.setBackground(new java.awt.Color(255, 102, 102));
        jTujuan5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jTujuan5);
        jTujuan5.setBounds(580, 150, 140, 30);

        jKedatangan5.setBackground(new java.awt.Color(255, 102, 102));
        jKedatangan5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jKedatangan5);
        jKedatangan5.setBounds(790, 150, 140, 30);

        jKeberangkatan5.setBackground(new java.awt.Color(255, 102, 102));
        jKeberangkatan5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jKeberangkatan5);
        jKeberangkatan5.setBounds(980, 150, 140, 30);

        jKereta6.setBackground(new java.awt.Color(255, 102, 102));
        jKereta6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jKereta6);
        jKereta6.setBounds(70, 180, 140, 30);

        jKelas6.setBackground(new java.awt.Color(255, 102, 102));
        jKelas6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jKelas6);
        jKelas6.setBounds(1180, 180, 150, 30);

        jRangkaian6.setBackground(new java.awt.Color(255, 102, 102));
        jRangkaian6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jRangkaian6);
        jRangkaian6.setBounds(250, 180, 140, 30);

        jAsal6.setBackground(new java.awt.Color(255, 102, 102));
        jAsal6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jAsal6);
        jAsal6.setBounds(410, 180, 140, 30);

        jTujuan6.setBackground(new java.awt.Color(255, 102, 102));
        jTujuan6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jTujuan6);
        jTujuan6.setBounds(580, 180, 140, 30);

        jKedatangan6.setBackground(new java.awt.Color(255, 102, 102));
        jKedatangan6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jKedatangan6);
        jKedatangan6.setBounds(790, 180, 140, 30);

        jKeberangkatan6.setBackground(new java.awt.Color(255, 102, 102));
        jKeberangkatan6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jKeberangkatan6);
        jKeberangkatan6.setBounds(980, 180, 140, 30);

        jKereta7.setBackground(new java.awt.Color(255, 102, 102));
        jKereta7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jKereta7);
        jKereta7.setBounds(70, 210, 140, 30);

        jRangkaian7.setBackground(new java.awt.Color(255, 102, 102));
        jRangkaian7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jRangkaian7);
        jRangkaian7.setBounds(250, 210, 140, 30);

        jAsal7.setBackground(new java.awt.Color(255, 102, 102));
        jAsal7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jAsal7);
        jAsal7.setBounds(410, 210, 140, 30);

        jTujuan7.setBackground(new java.awt.Color(255, 102, 102));
        jTujuan7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jTujuan7);
        jTujuan7.setBounds(580, 210, 140, 30);

        jKedatangan7.setBackground(new java.awt.Color(255, 102, 102));
        jKedatangan7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jKedatangan7);
        jKedatangan7.setBounds(790, 210, 140, 30);

        jKeberangkatan7.setBackground(new java.awt.Color(255, 102, 102));
        jKeberangkatan7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jKeberangkatan7);
        jKeberangkatan7.setBounds(980, 210, 140, 30);

        jKelas7.setBackground(new java.awt.Color(255, 102, 102));
        jKelas7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jKelas7);
        jKelas7.setBounds(1180, 210, 150, 30);

        jKereta8.setBackground(new java.awt.Color(255, 102, 102));
        jKereta8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jKereta8);
        jKereta8.setBounds(70, 240, 140, 30);

        jRangkaian8.setBackground(new java.awt.Color(255, 102, 102));
        jRangkaian8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jRangkaian8);
        jRangkaian8.setBounds(250, 240, 140, 30);

        jAsal8.setBackground(new java.awt.Color(255, 102, 102));
        jAsal8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jAsal8);
        jAsal8.setBounds(410, 240, 140, 30);

        jTujuan8.setBackground(new java.awt.Color(255, 102, 102));
        jTujuan8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jTujuan8);
        jTujuan8.setBounds(580, 240, 140, 30);

        jKedatangan8.setBackground(new java.awt.Color(255, 102, 102));
        jKedatangan8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jKedatangan8);
        jKedatangan8.setBounds(790, 240, 140, 30);

        jKeberangkatan8.setBackground(new java.awt.Color(255, 102, 102));
        jKeberangkatan8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jKeberangkatan8);
        jKeberangkatan8.setBounds(980, 240, 140, 30);

        jKelas8.setBackground(new java.awt.Color(255, 102, 102));
        jKelas8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jKelas8);
        jKelas8.setBounds(1180, 240, 150, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 250, 1320, 380);

        jLabel6.setIcon(new javax.swing.ImageIcon("E:\\Logo Kereta Api baru .png")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(1030, 50, 270, 150);

        jLabel8.setIcon(new javax.swing.ImageIcon("E:\\LOGO-TELKOM-SCHOOL.png")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(100, 50, 150, 150);

        setBounds(0, 0, 1369, 744);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if (jComboBox1.getSelectedItem().equals("-- Pilih Kereta --")){
             jKereta1.setText("");
             jRangkaian1.setText("");
             jAsal1.setText("");
             jTujuan1.setText("");
             jKedatangan1.setText("");
             jKeberangkatan1.setText("");
             jKelas1.setText("");
             
             jKereta2.setText("");
             jRangkaian2.setText("");
             jAsal2.setText("");
             jTujuan2.setText("");
             jKedatangan2.setText("");
             jKeberangkatan2.setText("");
             jKelas2.setText("");
             
             jKereta3.setText("");
             jRangkaian3.setText("");
             jAsal3.setText("");
             jTujuan3.setText("");
             jKedatangan3.setText("");
             jKeberangkatan3.setText("");
             jKelas3.setText("");
             
             jKereta4.setText("");
             jRangkaian4.setText("");
             jAsal4.setText("");
             jTujuan4.setText("");
             jKedatangan4.setText("");
             jKeberangkatan4.setText("");
             jKelas4.setText("");
             
             jKereta5.setText("");
             jRangkaian5.setText("");
             jAsal5.setText("");
             jTujuan5.setText("");
             jKedatangan5.setText("");
             jKeberangkatan5.setText("");
             jKelas5.setText("");
             
             jKereta6.setText("");
             jRangkaian6.setText("");
             jAsal6.setText("");
             jTujuan6.setText("");
             jKedatangan6.setText("");
             jKeberangkatan6.setText("");
             jKelas6.setText("");
             
             jKereta7.setText("");
             jRangkaian7.setText("");
             jAsal7.setText("");
             jTujuan7.setText("");
             jKedatangan7.setText("");
             jKeberangkatan7.setText("");
             jKelas7.setText("");
             
             jKereta8.setText("");
             jRangkaian8.setText("");
             jAsal8.setText("");
             jTujuan8.setText("");
             jKedatangan8.setText("");
             jKeberangkatan8.setText("");
             jKelas8.setText("");
        }else
        if(jComboBox1.getSelectedItem().equals("KA Dhoho / Penataran")){
             jKereta1.setText("Penataran");
             jRangkaian1.setText("441L/450");
             jAsal1.setText("Blitar (BL)");
             jTujuan1.setText("Surabaya Kota (SB)");
             jKedatangan1.setText("06.00 (WIB)");
             jKeberangkatan1.setText("06.02 (WIB)");
             jKelas1.setText("Ekonomi AC");
             
             jKereta2.setText("Dhoho");
             jRangkaian2.setText("449L/442");
             jAsal2.setText("Surabaya Kota (SB)");
             jTujuan2.setText("Blitar (BL)");
             jKedatangan2.setText("09.11 (WIB)");
             jKeberangkatan2.setText("09.14 (WIB)");
             jKelas2.setText("Ekonomi AC");
             
             jKereta3.setText("Penataran");
             jRangkaian3.setText("443/452");
             jAsal3.setText("Blitar (BL)");
             jTujuan3.setText("Surabaya Kota (SB)");
             jKedatangan3.setText("10.23 (WIB)");
             jKeberangkatan3.setText("10.26 (WIB)");
             jKelas3.setText("Ekonomi AC");
             
             jKereta4.setText("Dhoho");
             jRangkaian4.setText("451/444");
             jAsal4.setText("Surabaya Kota (SB)");
             jTujuan4.setText("Blitar (BL)");
             jKedatangan4.setText("13.20 (WIB)");
             jKeberangkatan4.setText("13.30 (WIB)");
             jKelas4.setText("Ekonomi AC");
             
             jKereta5.setText("Penataran");
             jRangkaian5.setText("445/454L");
             jAsal5.setText("Blitar (BL)");
             jTujuan5.setText("Surabaya Kota (SB)");
             jKedatangan5.setText("13.28 (WIB)");
             jKeberangkatan5.setText("13.32 (WIB)");
             jKelas5.setText("Ekonomi AC");
             
             jKereta6.setText("Dhoho");
             jRangkaian6.setText("453/446");
             jAsal6.setText("Surabaya Kota (SB)");
             jTujuan6.setText("Blitar (BL)");
             jKedatangan6.setText("16.23 (WIB)");
             jKeberangkatan6.setText("16.26 (WIB)");
             jKelas6.setText("Ekonomi AC");
             
             jKereta7.setText("Penataran");
             jRangkaian7.setText("447/456");
             jAsal7.setText("Blitar (BL)");
             jTujuan7.setText("Surabaya Kota (SB)");
             jKedatangan7.setText("17.35 (WIB)");
             jKeberangkatan7.setText("17.40 (WIB)");
             jKelas7.setText("Ekonomi AC");
             
             jKereta8.setText("Dhoho");
             jRangkaian8.setText("455/448");
             jAsal8.setText("Surabaya Kota (SB)");
             jTujuan8.setText("Blitar (BL)");
             jKedatangan8.setText("21.53 (WIB)");
             jKeberangkatan8.setText("21.55 (WIB)");
             jKelas8.setText("Ekonomi AC");
         }else
        if(jComboBox1.getSelectedItem().equals("KA Gajayana")){
             jKereta1.setText("Gajayana");
             jRangkaian1.setText("42");
             jAsal1.setText("Jakarta Gambir (GMR)");
             jTujuan1.setText("Malang Kotabaru (ML)");
             jKedatangan1.setText("06.48 (WIB)");
             jKeberangkatan1.setText("06.53 (WIB)");
             jKelas1.setText("Eksekutif Satwa");
             
             jKereta2.setText("Gajayana");
             jRangkaian2.setText("41");
             jAsal2.setText("Malang Kotabaru (ML)");
             jTujuan2.setText("Jakarta Gambir (GMR)");
             jKedatangan2.setText("15.49 (WIB)");
             jKeberangkatan2.setText("15.52 (WIB)");
             jKelas2.setText("Eksekutif Satwa");
             
             jKereta3.setText("");
             jRangkaian3.setText("");
             jAsal3.setText("");
             jTujuan3.setText("");
             jKedatangan3.setText("");
             jKeberangkatan3.setText("");
             jKelas3.setText("");
             
             jKereta4.setText("");
             jRangkaian4.setText("");
             jAsal4.setText("");
             jTujuan4.setText("");
             jKedatangan4.setText("");
             jKeberangkatan4.setText("");
             jKelas4.setText("");
             
             jKereta5.setText("");
             jRangkaian5.setText("");
             jAsal5.setText("");
             jTujuan5.setText("");
             jKedatangan5.setText("");
             jKeberangkatan5.setText("");
             jKelas5.setText("");
             
             jKereta6.setText("");
             jRangkaian6.setText("");
             jAsal6.setText("");
             jTujuan6.setText("");
             jKedatangan6.setText("");
             jKeberangkatan6.setText("");
             jKelas6.setText("");
             
             jKereta7.setText("");
             jRangkaian7.setText("");
             jAsal7.setText("");
             jTujuan7.setText("");
             jKedatangan7.setText("");
             jKeberangkatan7.setText("");
             jKelas7.setText("");
             
             jKereta8.setText("");
             jRangkaian8.setText("");
             jAsal8.setText("");
             jTujuan8.setText("");
             jKedatangan8.setText("");
             jKeberangkatan8.setText("");
             jKelas8.setText("");
         }else
        if (jComboBox1.getSelectedItem().equals("KA Majapahit")){
             jKereta1.setText("Majapahit");
             jRangkaian1.setText("150");
             jAsal1.setText("Jakarta Pasar ");
             jAsal2.setText(" Senen (PSE)");
             jTujuan1.setText("Malang Kotabaru (ML)");
             jKedatangan1.setText("07.24 (WIB)");
             jKeberangkatan1.setText("07.26 (WIB)");
             jKelas1.setText("Ekonomi AC Plus");
             
             jKereta3.setText("Majapahit");
             jRangkaian3.setText("149");
             jAsal3.setText("Malang Kotabaru (ML)");
             jTujuan3.setText("Jakarta Pasar ");
             jTujuan4.setText(" Senen (PSE)");
             jKedatangan3.setText("20.36 (WIB)");
             jKeberangkatan3.setText("20.39 (WIB)");
             jKelas3.setText("Ekonomi AC Plus");
             
             jKereta2.setText("");
             jRangkaian2.setText("");
             jTujuan2.setText("");
             jKedatangan2.setText("");
             jKeberangkatan2.setText("");
             jKelas2.setText("");
             
             jKereta4.setText("");
             jRangkaian4.setText("");
             jAsal4.setText("");
             jKedatangan4.setText("");
             jKeberangkatan4.setText("");
             jKelas4.setText("");
             
             jKereta5.setText("");
             jRangkaian5.setText("");
             jAsal5.setText("");
             jTujuan5.setText("");
             jKedatangan5.setText("");
             jKeberangkatan5.setText("");
             jKelas5.setText("");
             
             jKereta6.setText("");
             jRangkaian6.setText("");
             jAsal6.setText("");
             jTujuan6.setText("");
             jKedatangan6.setText("");
             jKeberangkatan6.setText("");
             jKelas6.setText("");
             
             jKereta7.setText("");
             jRangkaian7.setText("");
             jAsal7.setText("");
             jTujuan7.setText("");
             jKedatangan7.setText("");
             jKeberangkatan7.setText("");
             jKelas7.setText("");
             
             jKereta8.setText("");
             jRangkaian8.setText("");
             jAsal8.setText("");
             jTujuan8.setText("");
             jKedatangan8.setText("");
             jKeberangkatan8.setText("");
             jKelas8.setText("");
        }else
        if (jComboBox1.getSelectedItem().equals("KA Malabar")){
             jKereta1.setText("Malabar");
             jRangkaian1.setText("100L");
             jAsal1.setText("Bandung Hall (BD)");
             jTujuan1.setText("Malang Kotabaru (ML)");
             jKedatangan1.setText("05.25 (WIB)");
             jKeberangkatan1.setText("05.28 (WIB)");
             jKelas1.setText("Eksekutif, Bisnis ");
             jKelas2.setText(" & Ekonomi AC");
             
             jKereta3.setText("Malabar");
             jRangkaian3.setText("99");
             jAsal3.setText("Malang Kotabaru(ML)");
             jTujuan3.setText("Bandung Hall (BD)");
             jKedatangan3.setText("18.19 (WIB)");
             jKeberangkatan3.setText("18.21 (WIB)");
             jKelas3.setText("Eksekutif, Bisnis ");
             jKelas4.setText(" & Ekonomi AC");
             
             jKereta2.setText("");
             jRangkaian2.setText("");
             jAsal2.setText("");
             jTujuan2.setText("");
             jKedatangan2.setText("");
             jKeberangkatan2.setText("");

             
             jKereta4.setText("");
             jRangkaian4.setText("");
             jAsal4.setText("");
             jTujuan4.setText("");
             jKedatangan4.setText("");
             jKeberangkatan4.setText("");
             
             jKereta5.setText("");
             jRangkaian5.setText("");
             jAsal5.setText("");
             jTujuan5.setText("");
             jKedatangan5.setText("");
             jKeberangkatan5.setText("");
             jKelas5.setText("");
             
             jKereta6.setText("");
             jRangkaian6.setText("");
             jAsal6.setText("");
             jTujuan6.setText("");
             jKedatangan6.setText("");
             jKeberangkatan6.setText("");
             jKelas6.setText("");
             
             jKereta7.setText("");
             jRangkaian7.setText("");
             jAsal7.setText("");
             jTujuan7.setText("");
             jKedatangan7.setText("");
             jKeberangkatan7.setText("");
             jKelas7.setText("");
             
             jKereta8.setText("");
             jRangkaian8.setText("");
             jAsal8.setText("");
             jTujuan8.setText("");
             jKedatangan8.setText("");
             jKeberangkatan8.setText("");
             jKelas8.setText("");
        }else
        if (jComboBox1.getSelectedItem().equals("KA Malioboro Ekspres")){
             jKereta1.setText("Malioboro Ekspres");
             jRangkaian1.setText("104");
             jAsal1.setText("Yogyakarta Tugu (YK)");
             jTujuan1.setText("Malang Kotabaru (ML)");
             jKedatangan1.setText("01.41 (WIB)");
             jKeberangkatan1.setText("01.44 (WIB)");
             jKelas1.setText("Eksekutif & Ekonomi");
             jKelas2.setText("   AC Plus");
             
             jKereta3.setText("Malioboro Ekspres");
             jRangkaian3.setText("101");
             jAsal3.setText("Malang Kotabaru (ML)");
             jTujuan3.setText("Yogyakarta Tugu (YK)");
             jKedatangan3.setText("10.40 (WIB)");
             jKeberangkatan3.setText("10.43 (WIB)");
             jKelas3.setText("Eksekutif & Ekonomi");
             jKelas4.setText("   AC Plus");
             
             jKereta5.setText("Malioboro Ekspres");
             jRangkaian5.setText("102");
             jAsal5.setText("Yogyakarta Tugu (YK)");
             jTujuan5.setText("Malang Kotabaru (ML)");
             jKedatangan5.setText("13.10 (WIB)");
             jKeberangkatan5.setText("13.13 (WIB)");
             jKelas5.setText("Eksekutif & Ekonomi");
             jKelas6.setText("   AC Plus");
             
             jKereta7.setText("Maliobor Ekspres");
             jRangkaian7.setText("103");
             jAsal7.setText("Malang Kotabaru (ML)");
             jTujuan7.setText("Yogyakarta Tgu (YK)");
             jKedatangan7.setText("22.30 (WIB)");
             jKeberangkatan7.setText("22.33 (WIB)");
             jKelas7.setText("Eksekutif & Ekonomi");
             jKelas8.setText("   AC Plus");
             
             jKereta2.setText("");
             jRangkaian2.setText("");
             jAsal2.setText("");
             jTujuan2.setText("");
             jKedatangan2.setText("");
             jKeberangkatan2.setText("");
             
             jKereta4.setText("");
             jRangkaian4.setText("");
             jAsal4.setText("");
             jTujuan4.setText("");
             jKedatangan4.setText("");
             jKeberangkatan4.setText("");
             
             jKereta6.setText("");
             jRangkaian6.setText("");
             jAsal6.setText("");
             jTujuan6.setText("");
             jKedatangan6.setText("");
             jKeberangkatan6.setText("");
             
             jKereta8.setText("");
             jRangkaian8.setText("");
             jAsal8.setText("");
             jTujuan8.setText("");
             jKedatangan8.setText("");
             jKeberangkatan8.setText("");
        }else
        if (jComboBox1.getSelectedItem().equals("KA Matarmaja ")){
             jKereta1.setText("Matarmja");
             jRangkaian1.setText("172");
             jAsal1.setText("Jakarta Pasar ");
             jAsal2.setText(" Senen (PSE)");
             jTujuan1.setText("Malang Kotabaru (ML)");
             jKedatangan1.setText("04.49 (WIB)");
             jKeberangkatan1.setText("04.53 (WIB)");
             jKelas1.setText("Ekonomi AC");
             
             jKereta3.setText("Matarmaja");
             jRangkaian3.setText("171");
             jAsal3.setText("Malang Kotabaru (ML)");
             jTujuan3.setText("Jakarta Pasar ");
             jTujuan4.setText(" Senen (PSE)");
             jKedatangan3.setText("19.30 (WIB)");
             jKeberangkatan3.setText("19.33 (WIB)");
             jKelas3.setText("Ekonomi AC");
             
             jKereta2.setText("");
             jRangkaian2.setText("");
             jTujuan2.setText("");
             jKedatangan2.setText("");
             jKeberangkatan2.setText("");
             jKelas2.setText("");
             
             jKereta4.setText("");
             jRangkaian4.setText("");
             jAsal4.setText("");
             jKedatangan4.setText("");
             jKeberangkatan4.setText("");
             jKelas4.setText("");
             
             jKereta5.setText("");
             jRangkaian5.setText("");
             jAsal5.setText("");
             jTujuan5.setText("");
             jKedatangan5.setText("");
             jKeberangkatan5.setText("");
             jKelas5.setText("");
             
             jKereta6.setText("");
             jRangkaian6.setText("");
             jAsal6.setText("");
             jTujuan6.setText("");
             jKedatangan6.setText("");
             jKeberangkatan6.setText("");
             jKelas6.setText("");
             
             jKereta7.setText("");
             jRangkaian7.setText("");
             jAsal7.setText("");
             jTujuan7.setText("");
             jKedatangan7.setText("");
             jKeberangkatan7.setText("");
             jKelas7.setText("");
             
             jKereta8.setText("");
             jRangkaian8.setText("");
             jAsal8.setText("");
             jTujuan8.setText("");
             jKedatangan8.setText("");
             jKeberangkatan8.setText("");
             jKelas8.setText("");
        }
        
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tulungagung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tulungagung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tulungagung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tulungagung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tulungagung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAsal1;
    private javax.swing.JLabel jAsal2;
    private javax.swing.JLabel jAsal3;
    private javax.swing.JLabel jAsal4;
    private javax.swing.JLabel jAsal5;
    private javax.swing.JLabel jAsal6;
    private javax.swing.JLabel jAsal7;
    private javax.swing.JLabel jAsal8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jKeberangkatan1;
    private javax.swing.JLabel jKeberangkatan2;
    private javax.swing.JLabel jKeberangkatan3;
    private javax.swing.JLabel jKeberangkatan4;
    private javax.swing.JLabel jKeberangkatan5;
    private javax.swing.JLabel jKeberangkatan6;
    private javax.swing.JLabel jKeberangkatan7;
    private javax.swing.JLabel jKeberangkatan8;
    private javax.swing.JLabel jKedatangan1;
    private javax.swing.JLabel jKedatangan2;
    private javax.swing.JLabel jKedatangan3;
    private javax.swing.JLabel jKedatangan4;
    private javax.swing.JLabel jKedatangan5;
    private javax.swing.JLabel jKedatangan6;
    private javax.swing.JLabel jKedatangan7;
    private javax.swing.JLabel jKedatangan8;
    private javax.swing.JLabel jKelas1;
    private javax.swing.JLabel jKelas2;
    private javax.swing.JLabel jKelas3;
    private javax.swing.JLabel jKelas4;
    private javax.swing.JLabel jKelas5;
    private javax.swing.JLabel jKelas6;
    private javax.swing.JLabel jKelas7;
    private javax.swing.JLabel jKelas8;
    private javax.swing.JLabel jKereta1;
    private javax.swing.JLabel jKereta2;
    private javax.swing.JLabel jKereta3;
    private javax.swing.JLabel jKereta4;
    private javax.swing.JLabel jKereta5;
    private javax.swing.JLabel jKereta6;
    private javax.swing.JLabel jKereta7;
    private javax.swing.JLabel jKereta8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jRangkaian1;
    private javax.swing.JLabel jRangkaian2;
    private javax.swing.JLabel jRangkaian3;
    private javax.swing.JLabel jRangkaian4;
    private javax.swing.JLabel jRangkaian5;
    private javax.swing.JLabel jRangkaian6;
    private javax.swing.JLabel jRangkaian7;
    private javax.swing.JLabel jRangkaian8;
    private javax.swing.JLabel jTujuan1;
    private javax.swing.JLabel jTujuan2;
    private javax.swing.JLabel jTujuan3;
    private javax.swing.JLabel jTujuan4;
    private javax.swing.JLabel jTujuan5;
    private javax.swing.JLabel jTujuan6;
    private javax.swing.JLabel jTujuan7;
    private javax.swing.JLabel jTujuan8;
    // End of variables declaration//GEN-END:variables
}
